[workspace]
authors = ["eric-santos22 <ericduarteds@gmail.com>"]
channels = ["conda-forge"]
name = "pdi2_ime"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.14.3,<3.15"
opencv = ">=4.13.0,<5"
matplotlib = ">=3.10.8,<4"
numpy = ">=2.4.2,<3"
ipykernel = ">=7.2.0,<8"
